### ISSUE TITLE
Merges out of order

### ISSUE THREAD

**Issue by billsargent** [degoedel/ComicbookArchiveToolbox#3]
The merge merges out of order. Chapters 1 then 10-19 then 2 then 20-29.etc..

We need a way to rearrange the order :)

**Comment by degoedel** [comment]
Thanks. I’ll take a look at that as soon as I can.
Meanwhile you can "fix" the order by renaming the chapters with a "0" prefix before merging (chapters 01, 02, 03 instead of 1, 2, 3) so that every chapter number has the same number of digits.

**Comment by billsargent** [comment]
Thank you for taking the time to reply. I wasn't sure if this was being worked on any longer :) I'll do what you said though. Thanks so much

**Comment by degoedel** [comment]
To be fair, the project is inactive. I rarely use it, and it does what I need it to do (and more.. I did most of the modules for fun). But I’ll be happy to fix it or to improve it when I get feedback. It brings me joy to know that some people use it beside myself !

**Comment by degoedel** [comment]
v1.4 is available for download. You can now drag and drop files to reorder them in the selected files list before merging them.
Please try this new feature and tell me if it solves your issue, and I'll close this ticket.

**Comment by billsargent** [comment]
Thank works fantastic. Merged 97 chapters into one without a problem. :) Thanks for the help!
