### ISSUE TITLE
Doesn't Run

### ISSUE THREAD

**Issue by ReddPyramid** [degoedel/ComicbookArchiveToolbox#5]
The program won't run. I get the windows 'prevented this from running', tell it to run anyway, and............ nothing happens.  No process in task manager, no pop up, nothing. It doesn't *do* anything.

**Expected behavior**
Actually running.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome

**Comment by degoedel** [comment]
Hello, it most certainly is a .net framework version mismatch.
Try to upgrade to the latest version here : https://dotnet.microsoft.com/en-us/download/dotnet-framework
Should you already be up to date, or if it does not fix the problem, I will need more information.
Just after trying to run the app, open the windows event journal : press the windows key, type event and open the event viewer (I’m not sure of the english name, but you get the idea). There you can open the Windows Journal, and more specifically the Applications journal.
There should be an error notification in it at the top of the list or almost to the top.
Please copy the log and message in it and paste it here. I’ll see what I can do.

**Comment by degoedel** [comment]
I’ve found a way to reproduce the problem. I’ll let you know when I manage to fix it.

**Comment by degoedel** [comment]
Just a heads up : I’m still working on the crash. I have found a way to make it work, but it causes some issues in the interface. I hope to be able to release a new version in the coming weeks.

**Comment by degoedel** [comment]
I just published a new version of the app that you can download here : https://github.com/degoedel/ComicbookArchiveToolbox/files/9149276/ComicbookArchiveToolbox.v2.0.0.zip

It does require .Net 6.0 runtime (Desktop apps Version) : 
https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime

Please try it and tell me if it works for you, so that I may close this issue.
